# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sUvWABbCRkjHqbZIrCm1wqH0uzD78Hl9
"""

#import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data1 = pd.read_csv('/content/TTTTH.csv')
print(data1)

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

print(data1.isnull().sum())

data1['Unnamed: 12']

data1 = data1.rename(columns={
    'Unnamed: 15': 'Standard Amount',
    'Unnamed: 16': 'Standard Profit',
    'Unnamed: 17': 'Standard Quantity'
})

# Display the updated column names to confirm the change
print(data1.columns)

"""### Data Preparation for Cross-Validation

First, we need to prepare the data by handling missing values and selecting appropriate features and a target variable. I will drop the 'Unnamed: 12', 'Unnamed: 13', and 'Unnamed: 14' columns, as they contain many missing values and potentially non-numeric entries like `#DIV/0!` that would hinder model training. I will also convert any remaining `#DIV/0!` to `NaN` and drop those rows.

Then, I'll select 'Standard Amount' as our target variable (`y`) and 'Amount', 'Profit', and 'Quantity' as our features (`X`). For this initial setup, I'm focusing on numerical features. If you wish to include categorical features like 'Category' or 'Sub-Category', they would need to be encoded (e.g., using one-hot encoding).
"""

# Drop columns with many missing values or problematic data
data_cleaned = data1.drop(columns=['Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14'], errors='ignore')

# Convert any '#DIV/0!' strings to NaN in relevant columns before converting to numeric
for col in ['Standard Amount', 'Standard Profit', 'Standard Quantity']:
    if col in data_cleaned.columns:
        data_cleaned[col] = data_cleaned[col].replace('#DIV/0!', np.nan)

# Convert selected columns to numeric, coercing errors to NaN
for col in ['Amount', 'Profit', 'Quantity', 'Standard Amount', 'Standard Profit', 'Standard Quantity']:
    if col in data_cleaned.columns:
        data_cleaned[col] = pd.to_numeric(data_cleaned[col], errors='coerce')

# Drop rows where the target variable ('Standard Amount') is NaN after conversion
data_cleaned = data_cleaned.dropna(subset=['Standard Amount'])

# Define features (X) and target (y)
X = data_cleaned[['Amount', 'Profit', 'Quantity']]
y = data_cleaned['Standard Amount']

print(f"Shape of features (X): {X.shape}")
print(f"Shape of target (y): {y.shape}")
print("Missing values in X after cleanup:")
print(X.isnull().sum())
print("Missing values in y after cleanup:")
print(y.isnull().sum())

"""### K-Fold Cross-Validation

Now we will apply K-Fold cross-validation to evaluate the `GradientBoostingRegressor` model. We'll use 5 folds and `mean_squared_error` as the evaluation metric.
"""

from sklearn.model_selection import KFold

# Initialize the KFold object
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Initialize the GradientBoostingRegressor model
model = GradientBoostingRegressor(random_state=42)

# List to store mean squared errors for each fold
mse_scores = []

# Perform K-Fold cross-validation
for fold, (train_index, test_index) in enumerate(kf.split(X, y)):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Train the model
    model.fit(X_train, y_train)

    # Make predictions
    y_pred = model.predict(X_test)

    # Evaluate the model
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)
    print(f"Fold {fold+1}: Mean Squared Error = {mse:.4f}")

# Print the average and standard deviation of the MSE scores
print(f"\nAverage MSE across all folds: {np.mean(mse_scores):.4f}")
print(f"Standard Deviation of MSE across all folds: {np.std(mse_scores):.4f}")

import joblib

# Define the filename for saving the model
model_filename = 'gradient_boosting_model.joblib'

# Save the trained model
joblib.dump(model, model_filename)

print(f"Model successfully saved as '{model_filename}'")

"""### Using the Saved Model with Streamlit

To use the saved model in a Streamlit application, you will first need to download the `gradient_boosting_model.joblib` file from your Colab environment to your local machine or the environment where your Streamlit app will run.

Once downloaded, you can create a Python file (e.g., `streamlit_app.py`) with content similar to the following. This example demonstrates how to load the model and use it to make a prediction based on user input.
"""

!pip install streamlit

import streamlit as st
import joblib
import pandas as pd

# Load the trained model
model = joblib.load('gradient_boosting_model.joblib')

st.title('Sales Prediction App')
st.write('Enter the values below to get a sales prediction.')

# Input fields for features
amount = st.number_input('Amount', min_value=0.0, value=1000.0)
profit = st.number_input('Profit', min_value=0.0, value=100.0)
quantity = st.number_input('Quantity', min_value=0, value=5)

if st.button('Predict Standard Amount'):
    # Create a DataFrame from the input values
    input_data = pd.DataFrame([{
        'Amount': amount,
        'Profit': profit,
        'Quantity': quantity
    }])

    # Make prediction
    prediction = model.predict(input_data)[0]

    st.success(f'The predicted Standard Amount is: {prediction:.2f}')

st.markdown("""
To run this Streamlit app:
1. Save the code above into a file named `streamlit_app.py`.
2. Ensure `gradient_boosting_model.joblib` is in the same directory.
3. Run `streamlit run streamlit_app.py` in your terminal.
""")